name: Deploy ESNSeY Dashboard
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -r requirements.txt
          nohup python src/web/dashboard.py &
